const languages = {
  english: {
    languageLabel: 'English',

    //login/signUp/forgotPassword/verifyOTP/setPassword page Form
    firstName: 'First Name',
    middleName: 'Middle Name',
    lastName: 'Last Name',
    phoneNumber: 'Phone Number',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    signUp: 'Sign Up',
    login: 'Login',
    forgotPassword: 'Forgot Password',
    doYouHaveAnAccount: `Don't have an account`,
    submit: 'Submit',
    verifyOtp: 'Verify OTP',
    enterYourOtp: 'Enter Your OTP',
    newPassword: 'New Password',
    save: 'Save',

    //Personal Details setup screen
    skip: 'Skip',
    personalDetails: 'Personal Details',
    language: 'Language',
    gender: 'Gender',
    dob: 'DOB',
    height: 'Height',
    scanFeetSize: 'Scan Feet Size',
    addDevice: 'Add Device',

    //Home screen
    good: 'Good',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    night: 'Night',
    settings: 'Settings',
    hydration: 'Hydration',
    sleepTracking: 'Sleep Tracking',
    nutrition: 'Nutrition',
    workoutHome: 'Work Home',
    selfAssessment: 'Self Assessment',
    womenCycle: 'Women Cycle',
    typeSomethingHere: 'Type something here',
    viewActivities: 'View Activities',
    changeGoal: 'Change Goal',

    //Home activity carousel
    mindWellness: 'Mind Wellness',
    bodyMeasurement: 'Body Measurement',
    gaitAnalysis: 'Gait Analysis',
    vital: 'Vital',
    activity: 'Activity',

    //Settings screen
    profile: 'Profile',
    general: 'General',
    appearance: 'Appearance',
    homeScreen: 'Home Screen',
    battery: 'Battery',
    privacy: 'Privacy',
    notification: 'Notification',

    //Profile settings screen
    logOut: 'Log Out',
    dateOfBirth: 'Date Of Birth',
    emergencyPhone: 'Emergency Phone',
    deleteAccount: 'Delete Account',
    disableBiometric: 'Disable Biometric',
    enableBiometric: 'Enable Biometric',

    //General Settings Screen
    aboutUs: 'About Us',
    softwareUpdate: 'software Update',
    region: 'Region',

    //Appearance Settings Screen
    light: 'light',
    dark: 'dark',
    mode: 'mode',
    fontSize: 'Font Size',

    //Home Screen Settings Screen
    addToHomeScreen: 'Add To Home Screen',
    showOnHomeScreen: 'Show On Home Screen',

    //Battery Settings Screen
    shoebattery: 'Shoe Battery',
    powerMode: 'Power Mode',
    rate: 'Rate',
    heart: 'Heart',
    pulse: 'Pulse',
    bodyOxygen: 'Body Oxygen',
    bloodPressure: 'Blood Pressure',
    ecg: 'ECG',
    weightMonitor: 'Weight Monitor',
    temperature: 'Temperature',
    stepCount: 'Step Count',
    caloriesBurn: 'Calories Burn',
    bmi: 'BMI',
    bmr: 'BMR',

    //Privacy Settings Screen
    locationService: 'Location Settings',
    dataTracking: 'Data Tracking',
    emailId: 'Email ID',

    //Notification Settings Screen
    count: 'Count',
    list: 'List',
    scheduledSummary: 'Scheduled Summary',
    showPreviews: 'Show Previews',
    screenSharing: 'Screen Sharing',
    banners: 'Banners',
    sound: 'Sound',
    badges: 'Badges',

    //Food Scanner screen
    captureImageForFoodScanning: 'Capture Image For Food Scanning',
    chooseAnotherFood: 'Choose Another Food',

    //Mind Wellness Screen
    mindfullAndMeditation: 'Mind & Meditation',
    soothingSound: 'Soothing Sound',
    communitySupport: 'Community Support',
    copyingMechanism: 'Copying Mechanism',
    personalisedSetting: 'Personalised Setting',

    //Workout Home Screen
    workout: 'Workout',
    activities: 'Activities',
    gym: 'Gym',
    outdoor: 'Outdoor',
    yoga: 'Yoga',
    home: 'Home',

    //Change Goal Screen
    update: 'Update',
    steps: 'Steps',
    calories: 'Calories',
    sleep: 'Sleep',
    waterIntake: 'Water Intake',
    kcal: 'kcal',
    hours: 'hours',
    ltr: 'ltr',
  },
};

const labels = {
  languageLabel: 'languageLabel',
  firstName: 'firstName',
  middleName: 'middleName',
  lastName: 'lastName',
  phoneNumber: 'phoneNumber',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  signUp: 'SignUp',
  resetPassword: 'Reset Password',
  login: 'Login',
  forgotPassword: 'Forgot Password',
  doYouHaveAnAccount: 'doYouHaveAnAccount',
  submit: 'Submit',
  verifyOtp: 'Verify Otp',
  enterYourOtp: 'enterYourOtp',
  newPassword: 'newPassword',
  save: 'Save',
  skip: 'skip',
  personalDetails: 'personalDetails',
  language: 'language',
  gender: 'Gender',
  dob: 'dob',
  height: 'Height',
  scanFeetSize: 'scanFeetSize',
  addDevice: 'addDevice',
  good: 'good',
  morning: 'morning',
  afternoon: 'afternoon',
  evening: 'evening',
  night: 'night',
  settings: 'settings',
  hydration: 'Hydration',
  sleepTracking: 'sleepTracking',
  nutrition: 'nutrition',
  workoutHome: 'workoutHome',
  selfAssessment: 'selfAssessment',
  womenCycle: 'womenCycle',
  typeSomethingHere: 'typeSomethingHere',
  viewActivities: 'View Activities',
  mindWellness: 'Mind Wellness',
  bodyMeasurement: 'Body Measurement',
  gaitAnalysis: 'Gait Analysis',
  healthAnalysis: 'Health Report',
  vital: 'Vital',
  activity: 'Activity',
  profile: 'Profile',
  general: 'General',
  appearance: 'appearance',
  homeScreen: 'homeScreen',
  battery: 'battery',
  privacy: 'Privacy',
  notification: 'notification',
  logOut: 'Logout',
  dateOfBirth: 'dateOfBirth',
  emergencyPhone: 'emergencyPhone',
  deleteAccount: 'Delete Account',
  disableBiometric: 'disableBiometric',
  enableBiometric: 'Enable Biometric',
  aboutUs: 'About Us',
  softwareUpdate: 'Software Update',
  region: 'region',
  light: 'light',
  dark: 'dark',
  mode: 'mode',
  fontSize: 'fontSize',
  addToHomeScreen: 'addToHomeScreen',
  showOnHomeScreen: 'showOnHomeScreen',
  shoebattery: 'shoebattery',
  powerMode: 'powerMode',
  rate: 'rate',
  heart: 'heart',
  pulse: 'pulse',
  bodyOxygen: 'bodyOxygen',
  bloodPressure: 'bloodPressure',
  ecg: 'ecg',
  weightMonitor: 'weightMonitor',
  temperature: 'temperature',
  stepCount: 'Step Count',
  caloriesBurn: 'caloriesBurn',
  bmi: 'bmi',
  bmr: 'bmr',
  locationService: 'locationService',
  dataTracking: 'dataTracking',
  emailId: 'Email Id',
  scheduledSummary: 'scheduledSummary',
  showPreviews: 'showPreviews',
  screenSharing: 'screenSharing',
  banners: 'banners',
  sound: 'sound',
  badges: 'badges',
  captureImageForFoodScanning: 'captureImageForFoodScanning',
  mindfullAndMeditation: 'mindfullAndMeditation',
  soothingSound: 'soothingSound',
  communitySupport: 'communitySupport',
  copyingMechanism: 'copyingMechanism',
  personalisedSetting: 'personalisedSetting',
  workout: 'Workout',
  activities: 'activities',
  gym: 'gym',
  outdoor: 'outdoor',
  yoga: 'yoga',
  home: 'home',
  count: 'count',
  list: 'list',
  chooseAnotherFood: 'chooseAnotherFood',
  changeGoal: 'changeGoal',
  update: 'update',
  steps: 'steps',
  calories: 'calories',
  sleep: 'sleep',
  waterIntake: 'waterIntake',
  kcal: 'kcal',
  hours: 'hours',
  ltr: 'ltr',
  disconnect: 'Disconnect',
  insight: 'Insight',
  somthingwentwrong: 'Something went wrong',
  bodyWeight: 'body Weight',
  bodyScan: 'BodyScanning',
  analyzer: 'Analyzer',
  overallReport: 'Overall Report',
  caloriesCount: 'Calories Count',
  protine: 'Protine',
  fats: 'Fats',
  carbohydrate: 'Carbohydrates',
  bodyTempreature: 'Body Temprature',
  booldOxygen: 'Blood Oxygen',
  weight: 'Weight',
  poor: 'Poor',
  welcome: 'Welcome!',
  userName: 'User Name',
  noData: ' No data found.',
  monitorinig: 'Monitoring',
  lastMeasure: 'Last Measure:',
  average: 'Average',
  healthy: 'Healthy',
  maximnum: 'Maximum',
  danger: 'Danger',
  userInfo: 'User Information',
  age: 'Age',
  specialCondition: 'Special Condition',
  how: 'How?',
  what: 'What?',
  when: 'When?',
  signInWith: ' Sign in with ',
  dontHaveAccount: 'Dont Have An Account? ',
  scan: 'Scan',
};

export {languages, labels};
